window.B1_ACCESS_SETUP={
 firebase:{
  enabled:true,
  apiKey:"AIzaSyDB0HpnDXnfVda6syyoLvbbBcxjjSlP7Lc",
  authDomain:"book1-class-access.firebaseapp.com",
  projectId:"book1-class-access",
  appId:"1:214483233279:web:20c7352c4007fc01bddfca"
 },
 teacherEmail:"oohya330@gmail.com",
 firestoreDocument:"courseAccess/book1",
 defaults:{stages:{
  stage1:{label:"L1–R1",mode:"public",passwordHash:"",version:1},
  stage2:{label:"L4–R2",mode:"password",passwordHash:"",version:1},
  stage3:{label:"L7–R3",mode:"password",passwordHash:"",version:1}
 }},
 previewTeacherPassword:""
};