(function(){
"use strict";
const C=window.B1_ACCESS_SETUP;if(!C)return;
const P="B1FB2_",K={settings:P+"SETTINGS",teacher:P+"TEACHER",unlocks:P+"UNLOCKS"};
const norm=v=>String(v||"").trim().toLowerCase(),clone=o=>JSON.parse(JSON.stringify(o));
async function hash(v){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(norm(v)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function stage(path){const p=(path||location.pathname).toLowerCase();if(/\/(lesson-[123]|review-1)(\/|$)/.test(p))return"stage1";if(/\/(lesson-[456]|review-2)(\/|$)/.test(p))return"stage2";if(/\/(lesson-[789]|review-3)(\/|$)/.test(p))return"stage3";return null}
function unlocks(){try{return JSON.parse(localStorage.getItem(K.unlocks)||"{}")}catch{return{}}}
function saveUnlock(s,v){const u=unlocks();u[s]={version:v};localStorage.setItem(K.unlocks,JSON.stringify(u))}
function styles(){if(document.getElementById("b1fb2-style"))return;const s=document.createElement("style");s.id="b1fb2-style";s.textContent=`
.b1fb2-badge{position:absolute;right:13px;top:13px;z-index:20;padding:5px 9px;border:1px solid #d4dfd8;border-radius:999px;background:#fffefb;font:700 12px/1.2 "Microsoft JhengHei",sans-serif;color:#53675e}.b1fb2-dim{filter:saturate(.75);opacity:.87}
.b1fb2-tools{position:fixed;right:12px;bottom:12px;z-index:99990;display:flex;gap:7px;flex-wrap:wrap}.b1fb2-tools button,.b1fb2-panel button{border:1px solid #cad8d0;background:#fffefb;color:#50635a;border-radius:999px;padding:8px 11px;font:700 12px/1 "Microsoft JhengHei",sans-serif;cursor:pointer;box-shadow:0 5px 16px rgba(30,50,42,.09)}
.b1fb2-modal{position:fixed;inset:0;z-index:100000;display:grid;place-items:center;background:rgba(25,45,37,.34);padding:20px}.b1fb2-box{width:min(430px,92vw);background:#fffefb;border:1px solid #d8e2dc;border-radius:20px;padding:24px;box-shadow:0 22px 65px rgba(20,42,33,.2);font-family:"Microsoft JhengHei",sans-serif;color:#263c35}.b1fb2-box h2{margin:0 0 8px;font-size:21px}.b1fb2-box p{margin:0 0 12px;color:#6f7d77;line-height:1.5}.b1fb2-box input,.b1fb2-panel input,.b1fb2-panel select{width:100%;box-sizing:border-box;border:1px solid #cbd8d0;border-radius:10px;padding:10px 12px;font-size:15px;background:white}.b1fb2-hint{font-size:12px!important}.b1fb2-msg{min-height:20px;color:#a14e4e!important;font-size:13px}.b1fb2-actions{display:flex;justify-content:flex-end;gap:9px}.b1fb2-actions button{border:1px solid #bed0c5;border-radius:10px;padding:9px 14px;background:#edf5ef;color:#29483d;font-weight:800;cursor:pointer}.b1fb2-actions .sec{background:white}
.b1fb2-backdrop{position:fixed;inset:0;z-index:99998;background:rgba(25,45,37,.22)}.b1fb2-panel{position:fixed;left:50%;top:5vh;transform:translateX(-50%);z-index:99999;width:min(720px,94vw);max-height:90vh;overflow:auto;background:#fffefb;border:1px solid #d8e2dc;border-radius:22px;padding:22px;box-shadow:0 22px 70px rgba(20,42,33,.24);font-family:"Microsoft JhengHei",sans-serif;color:#263c35}.b1fb2-panel h2{margin:0 0 4px}.b1fb2-sub{margin:0 0 18px;color:#74817b;font-size:13px}.b1fb2-grid{display:grid;grid-template-columns:1.1fr .9fr 1fr;gap:12px;align-items:end;padding:14px 0;border-top:1px solid #edf0ed}.b1fb2-grid label{font-size:12px;color:#75817c;display:block;margin-bottom:5px}.b1fb2-title{font-weight:800;font-size:16px}.b1fb2-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.b1fb2-note{padding:10px 12px;border-radius:12px;background:#f2f6f3;color:#607068;font-size:13px;margin:12px 0}body.b1fb2-block>*:not(.b1fb2-modal):not(script){visibility:hidden!important}@media(max-width:650px){.b1fb2-grid{grid-template-columns:1fr}.b1fb2-panel{top:2vh;max-height:96vh}}
`;document.head.appendChild(s)}
function modal(title,text,opt={}){styles();const w=document.createElement("div");w.className="b1fb2-modal";w.innerHTML=`<div class="b1fb2-box"><h2>${title}</h2><p>${text}</p>${opt.input===false?"":'<input type="password" autocomplete="off"><p class="b1fb2-hint">英文字母不分大小寫</p>'}<p class="b1fb2-msg"></p><div class="b1fb2-actions"><button class="sec" data-cancel>取消</button><button data-ok>${opt.ok||"確認"}</button></div></div>`;document.body.appendChild(w);const i=w.querySelector("input"),m=w.querySelector(".b1fb2-msg"),close=()=>w.remove();w.querySelector("[data-cancel]").onclick=()=>{close();opt.cancel&&opt.cancel()};w.querySelector("[data-ok]").onclick=()=>opt.go&&opt.go(i?i.value:"",m,close);if(i){setTimeout(()=>i.focus(),20);i.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();w.querySelector("[data-ok]").click();}})}}
const B={
 mode:"preview",fb:null,user:null,
 async init(){if(!C.firebase.enabled)return;try{const v="12.19.0",a=await import(`https://www.gstatic.com/firebasejs/${v}/firebase-app.js`),u=await import(`https://www.gstatic.com/firebasejs/${v}/firebase-auth.js`),f=await import(`https://www.gstatic.com/firebasejs/${v}/firebase-firestore.js`);const app=a.initializeApp(C.firebase),auth=u.getAuth(app),db=f.getFirestore(app);this.fb={auth,db,u,f};this.user=auth.currentUser;u.onAuthStateChanged(auth,x=>this.user=x);this.mode="firebase"}catch(e){console.error(e);this.mode="error"}},
 async get(){if(this.mode==="error")throw Error("firebase-init-failed");if(this.mode==="preview"){try{return JSON.parse(localStorage.getItem(K.settings))||clone(C.defaults)}catch{return clone(C.defaults)}}const [col,id]=C.firestoreDocument.split("/"),r=this.fb.f.doc(this.fb.db,col,id),s=await this.fb.f.getDoc(r);return s.exists()?s.data():clone(C.defaults)},
 async save(x){const clean={stages:{stage1:x.stages.stage1,stage2:x.stages.stage2,stage3:x.stages.stage3}};if(this.mode==="preview"){localStorage.setItem(K.settings,JSON.stringify(clean));return}if(!this.fb.auth.currentUser)throw Error("login");const [col,id]=C.firestoreDocument.split("/");await this.fb.f.setDoc(this.fb.f.doc(this.fb.db,col,id),clean)},
 async teacher(){if(this.mode==="error")return false;return this.mode==="preview"?localStorage.getItem(K.teacher)==="1":!!this.fb.auth.currentUser},
 async login(p){if(this.mode==="error")return false;if(this.mode==="preview"){if(norm(p)===norm(C.previewTeacherPassword)){localStorage.setItem(K.teacher,"1");return true}return false}try{await this.fb.u.signInWithEmailAndPassword(this.fb.auth,C.teacherEmail,norm(p));return true}catch{return false}},
 async logout(){if(this.mode==="preview")localStorage.removeItem(K.teacher);else await this.fb.u.signOut(this.fb.auth)},
 async teacherPw(p){if(this.mode==="preview"){C.previewTeacherPassword=norm(p);return}await this.fb.u.updatePassword(this.fb.auth.currentUser,norm(p))}
};
let S;
async function load(){
  const raw=await B.get();
  const base=clone(C.defaults);
  const src=raw&&typeof raw==="object"?raw:{};
  const nested=src.stages&&typeof src.stages==="object"?src.stages:{};
  S={stages:{
    stage1:{...base.stages.stage1,...(nested.stage1||src.stage1||{})},
    stage2:{...base.stages.stage2,...(nested.stage2||src.stage2||{})},
    stage3:{...base.stages.stage3,...(nested.stage3||src.stage3||{})}
  }};
}
function status(s){const x=S.stages[s];if(x.mode==="public")return"公開";if(x.mode==="locked")return"尚未開放";const u=unlocks()[s];return u&&u.version===x.version?"已解鎖":"需密碼"}
async function ask(s,ok,cancel){const x=S.stages[s];if(await B.teacher())return ok();if(x.mode==="public")return ok();if(x.mode==="locked")return modal("目前尚未開放",`${x.label} 目前尚未開放。`,{input:false,ok:"返回",go:(v,m,c)=>{c();cancel&&cancel()}});const u=unlocks()[s];if(u&&u.version===x.version)return ok();modal(`解鎖 ${x.label}`,"請輸入本階段課程密碼。",{cancel,go:async(v,m,c)=>{if(await hash(v)===x.passwordHash){saveUnlock(s,x.version);c();ok()}else m.textContent="密碼錯誤，請再試一次。"}})}
function teacherLogin(){modal("教師登入","輸入教師密碼後，可直接開啟全部課程。",{go:async(v,m,c)=>{if(await B.login(v)){c();location.reload()}else m.textContent="教師密碼錯誤。"}})}
async function panel(){if(!(await B.teacher()))return teacherLogin();await load();styles();const d=document.createElement("div"),p=document.createElement("div");d.className="b1fb2-backdrop";p.className="b1fb2-panel";p.innerHTML=`<h2>教師控制台</h2><p class="b1fb2-sub">${B.mode==="firebase"?"Firebase 雲端同步":"本機預覽模式"}｜學生與教師密碼皆不分大小寫</p><div class="b1fb2-note">變更學生密碼後，該階段版本會自動更新，舊解鎖紀錄失效。</div><div data-list></div><div class="b1fb2-row"><button data-save>儲存設定</button><button data-tpw>修改教師密碼</button><button data-close>關閉</button></div><p class="b1fb2-sub" style="margin-top:14px">公開：直接進入｜需密碼：輸入階段密碼｜不公開：學生不可進入</p>`;document.body.append(d,p);const host=p.querySelector("[data-list]");Object.entries(S.stages).forEach(([k,x])=>{const r=document.createElement("div");r.className="b1fb2-grid";r.dataset.stage=k;r.innerHTML=`<div class="b1fb2-title">${x.label}</div><div><label>開放狀態</label><select data-mode><option value="public">公開</option><option value="password">需密碼</option><option value="locked">不公開</option></select></div><div><label>新學生密碼（留空＝不變）</label><input data-pw type="password" placeholder="英文字母不分大小寫"></div>`;r.querySelector("[data-mode]").value=x.mode;host.appendChild(r)});const close=()=>{p.remove();d.remove()};d.onclick=close;p.querySelector("[data-close]").onclick=close;p.querySelector("[data-save]").onclick=async()=>{const n=clone(S);for(const r of host.querySelectorAll("[data-stage]")){const k=r.dataset.stage,pw=r.querySelector("[data-pw]").value;n.stages[k].mode=r.querySelector("[data-mode]").value;if(pw.trim()){n.stages[k].passwordHash=await hash(pw);n.stages[k].version=(n.stages[k].version||0)+1}}try{await B.save(n);alert("設定已儲存。");close();location.reload()}catch{alert("儲存失敗，請確認 Firebase 權限設定。")}};p.querySelector("[data-tpw]").onclick=()=>modal("修改教師密碼","輸入新的教師密碼。",{go:async(v,m,c)=>{if(norm(v).length<6)return m.textContent="密碼至少 6 個字元。";try{await B.teacherPw(v);c();alert(B.mode==="firebase"?"教師密碼已更新。":"預覽模式：本次頁面有效。")}catch{m.textContent="修改失敗。"}}})}
async function refreshTeacherTools(){document.querySelectorAll(".b1fb2-tools").forEach(x=>x.remove());await tools()}
function tools(){styles();const b=document.createElement("div");b.className="b1fb2-tools";B.teacher().then(t=>{b.innerHTML=t?'<button data-panel>教師控制台</button><button data-out>登出</button><button data-reset>清除測試狀態</button>':'<button data-login>教師登入</button><button data-reset>清除測試狀態</button>';document.body.appendChild(b);b.querySelector("[data-login]")?.addEventListener("click",teacherLogin);b.querySelector("[data-panel]")?.addEventListener("click",panel);b.querySelector("[data-out]")?.addEventListener("click",async()=>{await B.logout();location.reload()});b.querySelector("[data-reset]").onclick=()=>{Object.keys(localStorage).filter(k=>k.startsWith(P)).forEach(k=>localStorage.removeItem(k));location.reload()}})}
async function home(){await B.init();await load();styles();for(const a of document.querySelectorAll("a.card[href]")){const s=stage(new URL(a.href,location.href).pathname);if(!s)continue;const t=await B.teacher(),b=document.createElement("span");b.className="b1fb2-badge";b.textContent=t?"教師可用":status(s);if(!t&&["需密碼","尚未開放"].includes(b.textContent))a.classList.add("b1fb2-dim");a.style.position=a.style.position||"relative";a.appendChild(b);a.addEventListener("click",e=>{e.preventDefault();ask(s,()=>location.href=a.href)})}tools()}
async function guard(){await B.init();await load();const s=stage(location.pathname);if(!s)return;document.body.classList.add("b1fb2-block");ask(s,()=>{document.body.classList.remove("b1fb2-block");tools()},()=>location.replace("../index.html"))}
window.B1FirebaseAccess={home,guard,panel};
})();